#Server
server:
  port: 8080

swagger:
  host: localhost:8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

mybatis:
  type-aliases-package: com.github.vsae.web
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
  max-size: 128MB

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-wait: 1ms
        max-active: 10
        max-idle: 8
        min-idle: 0
        shutdown-timeout: 100ms