#Server
server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root


mybatis:
  type-aliases-package: com.github.vsae.web
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
  max-size: 128MB

jwt:
  tokenHeader: Authorization
  secret: fm-secret
  expiration: 604800
  tokenHead: Bearer